export const vi = {
  home: "Trang chủ",
  services: "Dịch vụ",
  news: "Tin tức",
  careers: "Việc làm",
  contact: "Liên hệ",
  about: "Về chúng tôi",
  milestones: "Các cột mốc quan trọng",
  companies: "Công ty thành viên",
  leadership: "Khả năng lãnh đạo",

  menu: "Menu",
  sidebar: "Sidebar",
  dark_mode: "Dark mode",
  light_mode: "Light mode",
  default_mode: "Default mode",
  grey_mode: "Grey mode",
  classic_menu: "Classic menu",
  modern_menu: "Modern menu",

  search: "Tìm kiếm",
  submit: "Submit",
  save: "Save",
  cancel: "Cancel",
  close: "Close",

  msg_no_data_found: "No data found.",
  msg_search_result_sequence: "Items {0} to {1}.",
  msg_search_result_page_sequence: "Items {0} to {1} of {2}. Page {3} of {4}.",
  page_size: "Page Size",

  header_confirm: "Confirm",
  header_error: "Error",
  header_warning: "Warning",
  header_info: "Info",
  header_success: "Success",
  button_ok: "",
  button_yes: "Yes",
  button_no: "No",
  button_home: "Home",

  msg_confirm_save: "Bạn có chắc chắn là bạn muốn lưu không?",
  msg_save_success: "Dữ liệu đã được lưu thành công.",

  error_undefined: "{0} không được phép tồn tại.",
  error_exp: "{0} không khớp với biểu thức chính quy.",
  error_type: "Kiểu dữ liệu không hợp lệ. Kiểu của {0} không thể là {1}.",

  error_boolean: "{0} cannot be boolean.",
  error_strings: "{0} must be an string array.",
  error_numbers: "{0} must be an number array.",
  error_integers: "{0} must be an number array.",
  error_datetimes: "{0} must be an date time array.",
  error_dates: "{0} must be an date array.",

  error_required: "{0} là bắt buộc.",
  error_minlength: "{0} không được ít hơn {1} ký tự.",
  error_maxlength: "{0} không được nhiều hơn {1} ký tự.",

  error_email: "{0} không phải là địa chỉ email hợp lệ.",
  error_integer: "{0} không phải là số nguyên hợp lệ.",
  error_number: "{0} không phải là số hợp lệ.",
  error_precision: "{0} có độ chính xác không hợp lệ. Độ chính xác phải nhỏ hơn hoặc bằng {1}.",
  error_scale: "{0} có thang đo không hợp lệ. Thang đo phải nhỏ hơn hoặc bằng {1}.",
  error_phone: "{0} không phải là số điện thoại hợp lệ.",
  error_fax: "{0} không phải là số fax hợp lệ.",
  error_url: "{0} không phải là URL hợp lệ.",
  error_ipv4: "{0} không phải là địa chỉ IPv4 hợp lệ.",
  error_ipv6: "{0} không phải là địa chỉ IPv6 hợp lệ.",
  error_digit: "{0} must contain digits only.",
  error_dash_digit: "{0} must contain digits and dash only.",
  error_code: "{0} must contain characters and digits only.",
  error_dash_code: "{0} must contain characters and digits and dash only.",
  error_routing_number: "{0} is not a valid routing number.",
  error_check_number: "{0} is not a valid check number.",
  error_post_code: "{0} is not a valid post code.",
  error_ca_post_code: "{0} is not a valid Canada post code.",
  error_us_post_code: "{0} is not a valid US post code.",

  error_enum: "{0} phải là một trong các giá trị sau: {1}.",
  error_min: "{0} phải lớn hơn hoặc bằng {1}.",
  error_max: "{0} phải nhỏ hơn hoặc bằng {1}.",
  error_gt: "{0} must be greater than {1}.",
  error_lt: "{0} must be less than {1}.",
  error_equal: "{0} must be equal to {1}.",

  error_date: "{0} không phải là ngày hợp lệ.",
  error_min_date: "{0} cannot be before {1}.",
  error_max_date: "{0} cannot be after {1}.",
  error_from_now: "{0} must be after now.",
  error_from_tomorrow: "{0} must be from tomorrow.",
  error_from: "{0} must be after {1}.",
  error_after_now: "{0} cannot be after now.",
  error_after_tomorrow: "{0} cannot be after tomorrow.",
  error_after_yesterday: "{0} must be after yesterday.",
  error_after: "{0} cannot be after {1}.",

  error_400: "The server will not process the request due to the malformed request syntax.",
  error_401: "You have not logged in or the session was expired. Please log in." /* error_unauthorized */,
  error_403: "You do not have permission for this page or for this action." /* error_forbidden */,
  error_404: "The page is not found." /* error_not_found  */,
  error_409: "Request could not be processed because of conflict in the current state of the resource.",
  error_410: "The resource is no longer available at the server and no forwarding address is known.",

  error_network: "The network is down. Cannot connect to server.",
  error_response_body: "Error while processing the response body.",
  error_submit_failed: "Failed to submit data.",

  error_500: "Internal Server error",
  error_502: "Bad Gateway",
  error_503: "Service Unavailable",
  error_504: "Gateway Timeout",

  error_404_title: "404 Not found",
  error_404_message: "Xin lỗi, trang bạn đang tìm kiếm không tìm thấy.",
  error_500_title: "500 Internal Server Error",
  error_500_message: "Xin lỗi, máy chủ bị lỗi. Vui lòng thử lại sau.",

  keyword: "Keyword",

  country: "Quốc gia",
  company: "Công ty",
  email: "Thư điện tử",
  phone: "Số điện thoại",
  fullname: "Tên",
  job_title: "Chức danh",
  message: "Tin nhắn",

  published_at: "Đăng lúc",
  published_at_from: "Đăng sau khi",
  published_at_to: "Đăng trước khi",

  quantity: "Số lượng",
  location: "Vị trí",
  skills: "Kỹ năng",
  tags: "Thẻ",
  skill_placeholder: "Nhập kỹ năng...",
  tag_placeholder: "Nhập thẻ...",

  sort_time_desc: "Mới nhất",
  sort_time_asc: "Cũ nhất",
  
  sort_desc_time_desc: "Sắp xếp theo Mới nhất",
  sort_desc_time_asc: "Sắp xếp theo Cũ nhất",
}
